In [2]:
import numpy as np
arr=np.array([0,2,37,8])
print (type(arr))
print ("Array is ",arr)

Array is  [ 0  2 37  8]


In [13]:

print (arr.shape)
for i in range(len(arr)):
    print (arr[i])
arr[1]=70
print (arr)

(4,)
0
70
37
8
[ 0 70 37  8]


In [14]:
import numpy as np
arr1 = np.array([[0,1,2],[3,4,5]])
print ("Dimension of the array", arr1.shape)
print ("Elements of the 2D array",arr1) 

Dimension of the array (2, 3)
Elements of the 2D array [[0 1 2]
 [3 4 5]]


In [18]:
print (arr1[0, 0], arr1[0, 1], arr1[1, 0])

0 1 3


In [16]:
a = np.zeros((3,3))
print ("Inital array",a)

b = np.ones((2,2))
print (b)

c = np.full((3,2),9)
print (c)

d = np.random.random((3,3))
print (d)

e = np.eye(4)
print (e)

Inital array [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[9 9]
 [9 9]
 [9 9]]
[[0.5978504  0.16852965 0.40730106]
 [0.03155778 0.88647329 0.99612252]
 [0.05179086 0.71744941 0.84171598]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
x = np.zeros((3,3), dtype=[('a', np.int32), ('b', np.float64, (3,3))])
print ("x['a'].shape: ",x['a'].shape)
print ("(x['a'].dtype: ", x['a'].dtype)
print ("x['b'].shape: ", x['b'].shape)
print ("x['b'].dtype: ", x['b'].dtype)



x['a'].shape:  (3, 3)
(x['a'].dtype:  int32
x['b'].shape:  (3, 3, 3, 3)
x['b'].dtype:  float64


In [20]:
x = np.array([5, 6, 7, 8, 9])
print (x[1:5:1]    )    
print (x[-2:5])
print (x[-1:1:-1])

[6 7 8 9]
[8 9]
[9 8 7]


In [21]:
import numpy as np
g = np.arange(10)
print (g)

h = np.array([[0,1,2.0],[0,0,0],(1,3.,2.)])
print (h)

i = np.arange(1, 8, dtype=np.float)
print (i)
j = np.linspace(2., 4.,9)
print (j)
print ("Indices")
k = np.indices((3,2))

print ("Dimension is ",k.shape)
print (k)

[0 1 2 3 4 5 6 7 8 9]
[[0. 1. 2.]
 [0. 0. 0.]
 [1. 3. 2.]]
[1. 2. 3. 4. 5. 6. 7.]
[2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.  ]
Indices
Dimension is  (2, 3, 2)
[[[0 0]
  [1 1]
  [2 2]]

 [[0 1]
  [0 1]
  [0 1]]]
